Add `TARGET` param
concourse/builder-task pull request #20
Opened 2019-04-14 13:24 UTC by cirocosta

Previously, there was no way of having a particular stage
targetted when using the `build` script.

Being able to do so is particularly important for cases when
the default final stage does not need an intermediary testing
stage, meaning that such stage doesn't even get executed.

Now, with `--target`, one is able to have a task that explicitly
targets testing, leaving another task doing the default (or reaching
a `release` target).

For example:

```Dockerfile
FROM alpine AS build

	RUN echo "build" > /build

FROM alpine AS test

	RUN echo "test" > /test

FROM alpine AS release

	COPY --from=build /build /build
```

Without `--target`:

`build` and `release` are run.

With `--target=test`:

`test` is run.

Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>

2019-05-14 20:12 UTC, vito requested changes
makes sense, needs a rebase now tho

2019-05-14 20:12 UTC, vito commented on build
> +TARGET_OPT=$([[ ! -z "$TARGET" ]] && echo "--target $TARGET" || echo "")
This will fail due to `set -u`

2019-05-15 12:38 UTC, cirocosta commented on build
> +TARGET_OPT=$([[ ! -z "$TARGET" ]] && echo "--target $TARGET" || echo "")
oh, true!

2019-05-15 12:54 UTC, cirocosta commented
I'm having some trouble testing it as it seems like there's something misconfigured in `r.j3ss.co` 🤔 

```
docker pull r.j3ss.co/img:latest
Error response from daemon: Get https://r.j3ss.co/v2/img/manifests/latest: received unexpected HTTP status: 502 Bad Gateway
```

2019-05-15 12:55 UTC, cirocosta commented
ooooh just saw 3f7b49ea788bea90ad0a720493491a9f21bf2f1e

2019-05-15 13:04 UTC, cirocosta commented
Update: yeah, working well - would you mind reviewing it again, @vito? Thanks!

2019-05-15 13:13 UTC, vito approved these changes
👍 

side note: probably wise to get some sort of CI going for this repo soon

2019-05-15 13:14 UTC, merged